# Generated by Django 5.1.7 on 2026-05-02 03:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar_url', models.URLField(blank=True, max_length=500, null=True)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('website', models.URLField(blank=True)),
                ('github_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('github_username', models.CharField(blank=True, db_index=True, max_length=100)),
                ('github_url', models.URLField(blank=True)),
                ('github_token', models.CharField(blank=True, max_length=255)),
                ('is_github_connected', models.BooleanField(default=False)),
                ('total_contributions', models.IntegerField(db_index=True, default=0)),
                ('total_commits', models.IntegerField(default=0)),
                ('total_pull_requests', models.IntegerField(default=0)),
                ('total_issues', models.IntegerField(default=0)),
                ('total_reviews', models.IntegerField(default=0)),
                ('current_streak', models.IntegerField(default=0)),
                ('longest_streak', models.IntegerField(default=0)),
                ('last_streak_break', models.DateField(blank=True, null=True)),
                ('peak_contribution_time', models.CharField(blank=True, max_length=20)),
                ('top_language', models.CharField(blank=True, max_length=50)),
                ('momentum_score', models.FloatField(db_index=True, default=0.0)),
                ('momentum_consistency', models.FloatField(default=0.0)),
                ('momentum_recency', models.FloatField(default=0.0)),
                ('momentum_depth', models.FloatField(default=0.0)),
                ('momentum_decay', models.FloatField(default=1.0)),
                ('momentum_last_calculated', models.DateTimeField(blank=True, null=True)),
                ('personality_type', models.CharField(choices=[('explorer', 'Explorer'), ('specialist', 'Specialist'), ('maintainer', 'Maintainer'), ('sprinter', 'Sprinter'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('personality_confidence', models.FloatField(default=0.0)),
                ('personality_signals', models.JSONField(blank=True, default=dict)),
                ('burnout_risk', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=10)),
                ('burnout_signals', models.JSONField(blank=True, default=list)),
                ('daily_contributions', models.JSONField(blank=True, default=dict)),
                ('monthly_contributions', models.JSONField(blank=True, default=dict)),
                ('weekly_contributions', models.JSONField(blank=True, default=dict)),
                ('contribution_types', models.JSONField(blank=True, default=dict)),
                ('languages_used', models.JSONField(blank=True, default=dict)),
                ('language_stats', models.JSONField(blank=True, default=dict)),
                ('own_repos', models.JSONField(blank=True, default=list)),
                ('pinned_repos', models.JSONField(blank=True, default=list)),
                ('contributed_repos', models.JSONField(blank=True, default=list)),
                ('repo_health_cache', models.JSONField(blank=True, default=dict)),
                ('contribution_narrative', models.JSONField(blank=True, default=list)),
                ('consistency_rank', models.IntegerField(blank=True, null=True)),
                ('consistency_percentile', models.FloatField(blank=True, null=True)),
                ('twitter_handle', models.CharField(blank=True, max_length=100)),
                ('linkedin_url', models.URLField(blank=True)),
                ('email_verified', models.BooleanField(default=False)),
                ('profile_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_github_sync', models.DateTimeField(blank=True, null=True)),
                ('last_full_sync', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
        migrations.CreateModel(
            name='MomentumSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('score', models.FloatField()),
                ('consistency', models.FloatField(default=0.0)),
                ('recency', models.FloatField(default=0.0)),
                ('depth', models.FloatField(default=0.0)),
                ('decay', models.FloatField(default=1.0)),
                ('contributions_that_day', models.IntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='momentum_snapshots', to='app.userprofile')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['github_username'], name='app_userpro_github__35a30c_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['-momentum_score'], name='app_userpro_momentu_7f354b_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['-total_contributions'], name='app_userpro_total_c_59f784_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['personality_type'], name='app_userpro_persona_cf4bf7_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['top_language'], name='app_userpro_top_lan_25c7f1_idx'),
        ),
        migrations.AddIndex(
            model_name='momentumsnapshot',
            index=models.Index(fields=['profile', '-date'], name='app_momentu_profile_0b408c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='momentumsnapshot',
            unique_together={('profile', 'date')},
        ),
    ]
